<?php 
/* 
 * The settings file for white label: Aller media,  wl_id = 1,  2011-06-08 08:15:08 
 * This file is automatically generated from the db table 'settings'. 
 * Do not edit this file. Use the settings panel in the GUI 
 */ 

define("LAST_REG_ADD_DAYS", 5);
define("SEND_RESULT_EMAIL_ADD_DAYS", 3);
define("LAST_ADMIN_DAY_ADD_DAYS", 14);
define("MAX_NEW_PASS_ATTEMPTS", 3);
define("FRAUD_TIMESPAN_HOURS", 1);
define("NEW_PASS_LINK_VALID_HOURS", 6);
?>