-- Initial insert source for private person in Swedish.
-- delete from sources;
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'telefon', 'Telefon', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'direktreklam', 'Direktreklam', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tidningsannons', 'Tidningsannons', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tidningskupong', 'Tidningskupong', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'banner', 'Bannerannons på internet', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'bannerinyhetsbrev', 'Bannerannons i nyhetsbrev', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'sokmotor', 'Sökmotor', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tipsbekant', 'Tips från en bekant', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'event', 'Mässa eller event', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tidigarekund', 'Kund sedan tidigare', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'annat', 'Annat sätt', 'PRIVATE', CURDATE(), CURDATE());
-- Initial insert source for companys in Swedish.
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'telefon', 'Telefon', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'direktreklam', 'Direktreklam', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'kontorspost', 'Kontorspost', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tidningsannons', 'Tidningsannons', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tidningskupong', 'Tidningskupong', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'banner', 'Bannerannons på internet', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'bannerinyhetsbrev', 'Bannerannons i nyhetsbrev', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'sokmotor', 'Sökmotor', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'fax', 'Faxannons', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tipsbekant', 'Tips från en bekant', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'event', 'Mässa eller event', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'tidigarekund', 'Kund sedan tidigare', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(2, 'annat', 'Annat sätt', 'COMPANY', CURDATE(), CURDATE());
-- Initial insert source for private person in English.
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'phone', 'Phone', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'directadvertising', 'Direct advertising', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'newspaperad', 'Newspaper ad', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'newspapercoupon', 'Newspaper coupon', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'banner', 'Banner ad on the internet', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'bannerinthenewsletter', 'Banner in the newsletter', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'searchengine', 'Search engine', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'tipfromanacquaintance', 'Tip from an acquaintance', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'event', 'Fair or event', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'registeredclient', 'Registered client', 'PRIVATE', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'other', 'Other', 'PRIVATE', CURDATE(), CURDATE());
-- Initial insert source for companys in English.
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'phone', 'Phone', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'directadvertising', 'Direct advertising', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'officemail', 'Office mail', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'newspaperad', 'Newspaper ad', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'newspapercoupon', 'Newspaper coupon', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'banner', 'Banner ad on the internet', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'bannerinthenewsletter', 'Banner in the newsletter', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'searchengine', 'Search engine', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'fax', 'Fax', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'tipfromanacquaintance', 'Tip from an acquaintance', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'event', 'Fair or event', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'registeredclient', 'Registered client', 'COMPANY', CURDATE(), CURDATE());
insert into sources (wl_id, name, descr, type, created_at, updated_at) values(1, 'other', 'Other', 'COMPANY', CURDATE(), CURDATE());
-- Initial insert for Swedish municipals. The codes are taken from SCB
-- http://www.scb.se/Pages/List____257281.aspx
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0114', 'Upplands Väsby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0115', 'Vallentuna', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0117', 'Österåker', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0120', 'Värmdö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0123', 'Järfälla', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0125', 'Ekerö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0126', 'Huddinge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0127', 'Botkyrka', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0128', 'Salem', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0136', 'Haninge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0138', 'Tyresö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0139', 'Upplands-Bro', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0140', 'Nykvarn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0160', 'Täby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0162', 'Danderyd', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0163', 'Sollentuna', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0180', 'Stockholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0181', 'Södertälje', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0182', 'Nacka', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0183', 'Sundbyberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0184', 'Solna', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0186', 'Lidingö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0187', 'Vaxholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0188', 'Norrtälje', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0191', 'Sigtuna', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0192', 'Nynäshamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0305', 'Håbo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0319', 'Älvkarleby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0330', 'Knivsta', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0331', 'Heby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0360', 'Tierp', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0380', 'Uppsala', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0381', 'Enköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0382', 'Östhammar', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0428', 'Vingåker', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0461', 'Gnesta', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0480', 'Nyköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0481', 'Oxelösund', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0482', 'Flen', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0483', 'Katrineholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0484', 'Eskilstuna', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0486', 'Strängnäs', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0488', 'Trosa', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0509', 'Ödeshög', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0512', 'Ydre', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0513', 'Kinda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0560', 'Boxholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0561', 'Åtvidaberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0562', 'Finspång', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0563', 'Valdemarsvik', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0580', 'Linköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0581', 'Norrköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0582', 'Söderköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0583', 'Motala', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0584', 'Vadstena', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0586', 'Mjölby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0604', 'Aneby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0617', 'Gnosjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0642', 'Mullsjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0643', 'Habo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0662', 'Gislaved', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0665', 'Vaggeryd', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0680', 'Jönköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0682', 'Nässjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0683', 'Värnamo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0684', 'Sävsjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0686', 'Eksjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0687', 'Tranås', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0760', 'Uppvidinge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0761', 'Lessebo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0763', 'Tingsryd', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0764', 'Alvesta', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0765', 'Älmhult', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0767', 'Markaryd', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0780', 'Växjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0781', 'Ljungby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0821', 'Högsby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0834', 'Torsås', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0840', 'Mörbylånga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0860', 'Hultsfred', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0861', 'Mönsterås', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0862', 'Emmaboda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0880', 'Kalmar', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0881', 'Nybro', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0882', 'Oskarshamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0883', 'Västervik', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0884', 'Vimmerby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0885', 'Borgholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '0980', 'Gotland', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1060', 'Olofström', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1080', 'Karlskrona', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1081', 'Ronneby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1082', 'Karlshamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1083', 'Sölvesborg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1214', 'Svalöv', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1230', 'Staffanstorp', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1231', 'Burlöv', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1233', 'Vellinge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1256', 'Östra Göinge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1257', 'Örkelljunga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1260', 'Bjuv', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1261', 'Kävlinge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1262', 'Lomma', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1263', 'Svedala', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1264', 'Skurup', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1265', 'Sjöbo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1266', 'Hörby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1267', 'Höör', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1270', 'Tomelilla', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1272', 'Bromölla', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1273', 'Osby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1275', 'Perstorp', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1276', 'Klippan', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1277', 'Åstorp', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1278', 'Båstad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1280', 'Malmö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1281', 'Lund', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1282', 'Landskrona', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1283', 'Helsingborg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1284', 'Höganäs', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1285', 'Eslöv', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1286', 'Ystad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1287', 'Trelleborg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1290', 'Kristianstad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1291', 'Simrishamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1292', 'Ängelholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1293', 'Hässleholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1315', 'Hylte', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1380', 'Halmstad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1381', 'Laholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1382', 'Falkenberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1383', 'Varberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1384', 'Kungsbacka', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1401', 'Härryda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1402', 'Partille', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1407', 'Öckerö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1415', 'Stenungsund', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1419', 'Tjörn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1421', 'Orust', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1427', 'Sotenäs', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1430', 'Munkedal', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1435', 'Tanum', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1438', 'Dals-Ed', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1439', 'Färgelanda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1440', 'Ale', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1441', 'Lerum', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1442', 'Vårgårda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1443', 'Bollebygd', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1444', 'Grästorp', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1445', 'Essunga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1446', 'Karlsborg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1447', 'Gullspång', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1452', 'Tranemo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1460', 'Bengtsfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1461', 'Mellerud', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1462', 'Lilla Edet', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1463', 'Mark', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1465', 'Svenljunga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1466', 'Herrljunga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1470', 'Vara', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1471', 'Götene', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1472', 'Tibro', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1473', 'Töreboda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1480', 'Göteborg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1481', 'Mölndal', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1482', 'Kungälv', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1484', 'Lysekil', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1485', 'Uddevalla', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1486', 'Strömstad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1487', 'Vänersborg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1488', 'Trollhättan', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1489', 'Alingsås', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1490', 'Borås', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1491', 'Ulricehamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1492', 'Åmål', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1493', 'Mariestad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1494', 'Lidköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1495', 'Skara', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1496', 'Skövde', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1497', 'Hjo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1498', 'Tidaholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1499', 'Falköping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1715', 'Kil', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1730', 'Eda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1737', 'Torsby', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1760', 'Storfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1761', 'Hammarö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1762', 'Munkfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1763', 'Forshaga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1764', 'Grums', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1765', 'Årjäng', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1766', 'Sunne', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1780', 'Karlstad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1781', 'Kristinehamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1782', 'Filipstad', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1783', 'Hagfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1784', 'Arvika', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1785', 'Säffle', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1814', 'Lekeberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1860', 'Laxå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1861', 'Hallsberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1862', 'Degerfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1863', 'Hällefors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1864', 'Ljusnarsberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1880', 'Örebro', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1881', 'Kumla', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1882', 'Askersund', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1883', 'Karlskoga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1884', 'Nora', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1885', 'Lindesberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1904', 'Skinnskatteberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1907', 'Surahammar', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1960', 'Kungsör', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1961', 'Hallstahammar', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1962', 'Norberg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1980', 'Västerås', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1981', 'Sala', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1982', 'Fagersta', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1983', 'Köping', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '1984', 'Arboga', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2021', 'Vansbro', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2023', 'Malung-Sälen', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2026', 'Gagnef', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2029', 'Leksand', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2031', 'Rättvik', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2034', 'Orsa', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2039', 'Älvdalen', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2061', 'Smedjebacken', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2062', 'Mora', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2080', 'Falun', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2081', 'Borlänge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2082', 'Säter', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2083', 'Hedemora', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2084', 'Avesta', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2085', 'Ludvika', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2101', 'Ockelbo', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2104', 'Hofors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2121', 'Ovanåker', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2132', 'Nordanstig', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2161', 'Ljusdal', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2180', 'Gävle', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2181', 'Sandviken', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2182', 'Söderhamn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2183', 'Bollnäs', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2184', 'Hudiksvall', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2260', 'Ånge', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2262', 'Timrå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2280', 'Härnösand', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2281', 'Sundsvall', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2282', 'Kramfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2283', 'Sollefteå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2284', 'Örnsköldsvik', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2303', 'Ragunda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2305', 'Bräcke', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2309', 'Krokom', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2313', 'Strömsund', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2321', 'Åre', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2326', 'Berg', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2361', 'Härjedalen', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2380', 'Östersund', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2401', 'Nordmaling', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2403', 'Bjurholm', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2404', 'Vindeln', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2409', 'Robertsfors', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2417', 'Norsjö', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2418', 'Malå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2421', 'Storuman', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2422', 'Sorsele', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2425', 'Dorotea', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2460', 'Vännäs', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2462', 'Vilhelmina', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2463', 'Åsele', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2480', 'Umeå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2481', 'Lycksele', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2482', 'Skellefteå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2505', 'Arvidsjaur', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2506', 'Arjeplog', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2510', 'Jokkmokk', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2513', 'Överkalix', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2514', 'Kalix', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2518', 'Övertorneå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2521', 'Pajala', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2523', 'Gällivare', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2560', 'Älvsbyn', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2580', 'Luleå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2581', 'Piteå', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2582', 'Boden', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2583', 'Haparanda', CURDATE(), CURDATE());
insert into municipals (country_id, code, name,  created_at, updated_at) values(46, '2584', 'Kiruna', CURDATE(), CURDATE());